var arraysCamposVisivel = ["B1_COD","B1_DESC","B1_TIPO","B1_UM","B1_LOCPAD","B1UM","B1TIPO","B1TIPOBN","B1_PROD","B1_ALTER","B1_CC","B1_CLVL","B1_COD",
   "B1_CODBAR","B1_CODGTIN","B1_CODITE","B1_COMIS","B1_CONINI","B1_CONTA","B1_CONV","B1_CUSTD","B1_DATREF","B1_DESC","B1_DESC_GI","B1_DESC_I","B1_DESC_P","B1_DTREFP1","B1_ESPECIF","B1_FORMLOT","B1_FPCOD","B1_GRUPCOM","B1_GRUPO","B1_ITEMCC","B1_LOCPAD","B1_LOJPROC","B1_MAT_PRI","B1_OPC","B1_PERINV","B1_PESO","B1_POTENCI","B1_PROC","B1_PRV1","B1_QB","B1_QBP","B1_REVATU","B1_SEGUM","B1_TE",
   "B1_TIPO","B1_TS","B1_UCALSTD","B1_UCOM","B1_UM","B1_UPRC","B1_UREV","B1_VLREFUS","B1_BITMAP","B1_CODOBS","B1_OBS","B1_SITPROD","B1_CONTCQP","B1_NOTAMIN","B1_NUMCQPR","B1_EDICAO","B1_FAIXAS","B1_ISBN","B1_LINGUA","B1_NROPAG","B1_OBSISBN","B1_QTDACUM","B1_QTDINIC","B1_SERIE","B1_TITORIG","B1_PERGART","B1_AFABOV","B1_AFACS","B1_AFAMAD",
   "B1_AFETHAB","B1_ALFECRN","B1_ALIQISS","B1_CLASFIS","B1_CLASSE","B1_CNAE","B1_CODISS","B1_CRDEST","B1_CRDPRES","B1_ESPECIE","B1_EX_NBM","B1_EX_NCM","B1_FECP","B1_GRTRIB","B1_INT_ICM","B1_IPI","B1_ORIGEM","B1_PCOFINS","B1_PCSLL","B1_PICM","B1_PICMENT","B1_PICMRET","B1_POSIPI","B1_PPIS","B1_PRFDSUL","B1_QTMIDIA","B1_REDCOF","B1_REDINSS","B1_REDIRRF","B1_REDPIS","B1_REGRISS","B1_TAB_IPI","B1_TRIBMUN",
   "B1_VLR_COF","B1_VLR_ICM","B1_VLR_IPI","B1_VLR_PIS","B1_VLRSELO","B1_ATRIB1","B1_ATRIB2","B1_ATRIB3","B1_CORPRI","B1_CORSEC","B1_EMAX","B1_EMIN","B1_ESTFOR","B1_ESTRORI","B1_ESTSEG","B1_FORPRZ","B1_LE","B1_LM","B1_LOTESBP","B1_NICONE","B1_OPERPAD","B1_PE","B1_PRVALID","B1_QE","B1_REGSEQ","B1_TOLER","B1_AFASEMT","B1_AFUNDES","B1_AIMAMT","B1_ALADI","B1_ALFECOP","B1_ALFECST","B1_ALFUMAC",
   "B1_BASE","B1_BASE2","B1_BASE3","B1_CCCUSTO","B1_CEST","B1_CFEMA","B1_CHASSI","B1_CODANT","B1_CODEMB","B1_CODLAN","B1_CODNOR","B1_CODPROC","B1_CODQAD","B1_COEFDCR","B1_COLOR","B1_DATASUB","B1_DCR","B1_DCRE","B1_DCRII","B1_DESBSE2","B1_DESBSE3","B1_DIFCNAE","B1_DTCORTE","B1_FABRIC","B1_FECPBA","B1_FILIAL","B1_FRACPER","B1_GCCUSTO","B1_GDODIF","B1_GRPCST",
   "B1_GRPTI","B1_GRUDES","B1_IAT","B1_IDHIST","B1_IMPNCM","B1_IPPT","B1_LOTVEN","B1_MARKUP","B1_MODELO","B1_MOPC","B1_NALNCCA","B1_NALSH","B1_NUMCOP","B1_OK","B1_PAFMD5","B1_PARCEI","B1_PAUTFET","B1_PESBRU","B1_PMACNUT","B1_PMICNUT","B1_PR43080","B1_PRDORI",
   "B1_PRINCMG","B1_PRODPAI","B1_SELOEN","B1_SETOR","B1_SITTRIB","B1_TALLA","B1_TECLA","B1_TIPCAR","B1_TIPOBN","B1_TIPVEC","B1_TNATREC","B1_TPPROD","B1_UMOEC","B1_USERLGA","B1_USERLGI","B1_UVLRC","B1_VEREAN","B1_VIGENC","B1_VLCIF","B1_TFETHAB","B1_QTDSER","B1_IMPZFRC","B1_GARANT",
   "B1_VM_GI","B1_VM_I","B1_VM_P","B1_VM_PROC","B1_X_APP","A1_PESSOA","B1_INTEG","B1_PORCPRL","B1_PRODREC","B1_TIPCONV","B1_INSS","B1_DESPIMP","B1_MRP","B1_RPRODEP","B1_REQUIS","B1_RETOPER","B1_CSLL","B1_MSBLQL","B1_APROPRI","B1_TIPODEC","B1_CONTSOC","B1_IRRF","B1_TIPOCQ","B1_SOLICIT","B1_CPOTENC","B1_COFINS","B1_FETHAB","B1_CFEM",
   "B1_DCI","B1_IVAAJU","B1_PIS","B1_MIDIA","B1_IMPORT","B1_MONO","B1_TIPE","B1_QUADPRO","B1_FAMILIA","B1_MEPLES","B1_CLASSVE","B1_FECOP","B1_RASTRO","B1_REFBAS","B1_AJUDIF","B1_LOCALIZ","B1_REGESIM","B1_AGREGCU","B1_FUSTF","B1_SELO","B1_MCUSTD","B1_ESCRIPI","B1_CARGAE","B1_PRN944I","B1_ENVOBR",
   "B1_GRADE","B1_FLAGSUG","B1_USAFEFO","B1_CRICMS","B1_FANTASM","B1_PRODSBP","B1_CRICMST","B1_ANUENTE","B1_FORAEST","B1_CFEMS","B1_RICM65","B1_VALEPRE","B1_FRETISS","B1_BALANCA","B1_TPDP","B1_CALCFET","B1_CONTRAT","B1_TPREG","B1_RSATIVO",
   "B1UM","B1LOCPAD","B1GRUPO","B1TE","B1TS","B1SEGUM","B1ALTER","B1CONTA","B1CC","B1ITEMCC","B1PROC","B1FORMLOT",
   "B1GRUPO","B1LOCPAD","B1GRUPCOM","B1CLVL","B1POSIPI","B1CODISS","B1ORIGEM","B1GRTRIB","B1TABIPI","B1CLASSE","B1ESTFOR","B1FORPRZ","B1TIPCAR",
   "B1TNATREC","B5ONU","B1GCCUSTO","B1PARCEI","B1CCCUSTO","B1CODQAD","B1TIPOBN","B5UMDIPI","B1GRPCST","B1TPPROD","B1CODANT","B1GRPTI","B1PRDORI"];
    //  "B5_COD","B5_CEME","B5_PROPOR1","B5_PROPOR2","B5_CRDEST1","B5_CRDEST2","B5_FTIF","B5_FTIN",
  //  "B5_USOITE","B5_CODISRF","B5_VOLRECI","B5_DIASHL","B5_INSUMO","B5_REVPROD","B5_CODTRAM","B5_TPSERV","B5_INDPETR","B5_DENSID",
  //  "B5_DTDECRE","B5_EMBAGRO","B5_REGMAPA","B5_PRODDNF","B5_INSSPAT","B5_PINSUMO","B5_BENDL","B5_IMPGRUP","B5_INTDI","B5_CONCENT",
  //  "B5_ZF4PORC","B5_AM4PORC","B5_LOCALIZ","B5_CODCAI","B5_VOLUME","B5_AMMULTS","B5_CONCEN","B5_DESCSER","B5_FILIAL","B5_LOCALI2",
  //  "B5_CODTP","B5_CMPEXTR","B5_CDDMDBA","B5_PERIOT","B5_ALTURLC","B5_SITDIEF","B5_DESCNFE","B5_TABINC","B5_CODGRU","B5_FORCAO","B5_MARCA","B5_SERSCD",
  //  "B5_FCIPRV","B5_ZFMULTO","B5_ZFMULTS","B5_DIASHF","B5_VLZERO","B5_2CODBAR","B5_NATBEN","B5_DTDECAL","B5_FUNCEP","B5_ECBENFI",
  //  "B5_NUMBEN","B5_ANOBEN","B5_TPESOC","B5_MARGPRE","B5_VLRCID","B5_ECEAN1","B5_ENVMKT","B5_ECDESF","B5_INDCPRB",
  //  "B5_NBS","B5_CODATIV","B5_CODSERC","B5_CATMAT","B5_CDFATD","B5_CODGNRE","B5_CODFAM","B5_DEC7174","B5_CLASSE","B5_ECALTEM",
  //  "B5_AMMULTO","B5_FORSER","B5_PROTOTI","B5_PRZCQ","B5_MARPEC","B5_MONTA","B5_PROJDES","B5_IDHIST","B5_EAN145",
  //  "B5_VERIND","B5_NRECAGR","B5_INGATV","B5_REDALIQ","B5_ISEN","B5_NUMBEAL","B5_NATALBE","B5_TPAPUR",
  //  "B5_CODITE","B5_FORMMRP","B5_AGLUMRP","B5_CTRWMS","B5_PRV2","B5_PROTCON","B5_TIPO","B5_GRPIVA","B5_FPRZCQ","B5_CTVAR","B5_CATEG",
  //  "B5_PRV7","B5_CODCLI","B5_VERSAO","B5_BLQINVA","B5_ALTTRIB","B5_BLQINVD","B5_CODLIN","B5_DTREFP7","B5_EMB1","B5_EMB2",
  //  "B5_QE1","B5_QE2","B5_COMPRLC","B5_CTDACON","B5_ECSUBT","B5_ISDSHIP","B5_EMPMAX","B5_ROTACAO","B5_INSPAT","B5_CERT",
  //  "B5_SERVINT","B5_COMPR","B5_NPULMAO","B5_DES","B5_WMSEMB","B5_COMPEND","B5_ARREQTD","B5_ESPESS","B5_ESTMAT","B5_LARG",
  //  "B5_CONVDIP","B5_SERVTDV","B5_ENDSAI","B5_SERVDEV","B5_SERVREQ","B5_ENDENT","B5_ENDREQ","B5_ENDDEV","B5_CARPER","B5_IDADEM",
  //  "B5_LVLEMB","B5_LPSEMB","B5_PERCUB","B5_PORTMS","B5_UMDIPI","B5_ITEM","B5_CALORIA","B5_PESO","B5_TOTGOR","B5_DIASES",
  //  "B5_PRV3","B5_PRV4","B5_PRV5","B5_MODELO","B5_ESPECIE","B5_QUALIDA","B5_EAN141","B5_PRV6","B5_DTREFP2","B5_DTREFP3",
  //  "B5_DTREFP4","B5_DTREFP5","B5_DTREFP6","B5_TIPUNIT","B5_LARGLC","B5_IMPETI","B5_VLDOPER","B5_VLDREQ","B5_ENDECD",
  //  "B5_SEMENTE","B5_LEADTR","B5_FATARMA","B5_UMIND","B5_SERVENT","B5_TAKEUP","B5_TPCOMMO","B5_SERVSAI","B5_SERVEMB", 
  //  "B5_ENDSCD","B5_ISIDUNI","B5_GSLE","B5_GSMC","B5_GSMI","B5_TPISERV","B5_ECDESCR","B5_ECENQUA","B5_ECPESOE",
  //  "B5_ECSEQ","B5_ECLARGE","B5_ECINDIC","B5_ECLARGU","B5_ECTITU","B5_ECPCHAV","B5_ECSEQ2","B5_ECCOMP","B5_ECPROFU", 
  //  "B5_ECCARAC","B5_ECCUBAG","B5_ECDTEX2","B5_ECDTLAN","B5_ECFLAG","B5_ECDTEX","B5_ECIMGFI","B5_ECAPRES","B5_SERECD", 
  //  "B5_ONU","B5_TOTGORS","B5_TOTGORT","B5_COR","B5_ALTURA","B5_EAN142","B5_EAN143","B5_EAN144","B5_EAN146","B5_EAN147",
  //  "B5_EAN148","B5_QTDVAR","B5_DTINV","B5_CODZON","B5_PENE","B5_TRATAM","B5_CLAUBA","B5_UMPRC","B5_DESTRAT","B5_CULTRA",
  //  "BZ_FILIAL","BZ_COD","BZ_LOCPAD","BZ_TE","BZ_TS","BZ_AFUNDES","BZ_ALFECRN","BZ_ALFUMAC","BZ_ALIQISS","BZ_COFINS",
  //  "BZ_CONINI","BZ_CONVDIP","BZ_CSLL","BZ_CTRWMS","BZ_CUSTD","BZ_DATREF","BZ_DTINCLU","BZ_EMAX","BZ_EMIN","BZ_ESTFOR","BZ_ESTSEG","BZ_FANTASM","BZ_FCIPRV","BZ_FECP","BZ_FECPBA",
  //  "BZ_FORPRZ","BZ_GRTRIB","BZ_HABDIF","BZ_HORFIX","BZ_IDHIST","BZ_IMPNCM","BZ_INT_ICM","BZ_IPI","BZ_IRRF","BZ_LE","BZ_LM","BZ_LOCALI2","BZ_LOCALIZ","BZ_MARKUP","BZ_MCUSTD","BZ_MOPC",
  //  "BZ_MRP","BZ_OPC","BZ_ORIGEM","BZ_PCOFINS","BZ_PCSLL","BZ_PE","BZ_PICM","BZ_PICMENT","BZ_PICMRET","BZ_PIS","BZ_PPIS","BZ_QB","BZ_QBP","BZ_QE","BZ_REDCOF","BZ_REDPIS","BZ_REVATU",
  //  "BZ_TIPE","BZ_TIPOCQ","BZ_TOLER","BZ_TPHOFIX","BZ_TRIBMUN","BZ_UCALSTD","BZ_UCOM","BZ_UPRC","BZ_VLR_ICM","BZ_VLR_IPI"]; 




var arraysCamposOculto = [
//   "B1_TIPO", "B1_UM", "B1_LOCPAD", "B1_GRUPO", "B1_TE", "B1_TS", "B1_SEGUM", "B1_ALTER",
// "B1_CONTA", "B1_CC", "B1_ITEMCC", "B1_PROC", "B1_FORMLOT", "B1_GRUPCOM", "B1_CLVL", "B1_POSIPI", "B1_CODISS",
// "B1_ORIGEM", "B1_GRTRIB", "B1_TABIPI", "B1_CLASSE", "B1_ESTFOR", "B1_FORPRZ", "B1_TIPCAR", "B1_TNATREC", "B1_GCCUSTO", "B1_CCCUSTO", 
// "B1_PARCEI", "B1_CODQAD", "B1_TIPOBN", "B1_GRPCST", "B1_TPPROD", "B1_CODANT", "B1_GRPTI", "B1_PRDORI" 
]; 

var arraysCamposObr = []; 

var arraysCamposZooms = ["B1_TIPO","BZ_LOCPAD","B1_UM","B1_LOCPAD","B1_GRUPO","B1_TE","B1_TS","B1_SEGUM","B1_ALTER","B1_CONTA","B1_CC","B1_ITEMCC","B1_PROC","B1_FORMLOT",
  "B1_GRUPCOM","B1_CLVL","B1_POSIPI","B1_CODISS","B1_ORIGEM","B1_GRTRIB","B1_TABIPI","B1_CLASSE","B1_ESTFOR","B1_FORPRZ","B1_TIPCAR",
"B1_TNATREC","B5_ONU","B1_GCCUSTO","B1_PARCEI","B1_CCCUSTO","B1_CODQAD","B1_TIPOBN","B5_UMDIPI","B1_GRPCST","B1_TPPROD","B1_CODANT","B1_GRPTI","B1_PRDORI"
]; 

var arraysCamposZoomConslt = ["B1TIPO","BZLOCPAD","B1UM","B1LOCPAD","B1GRUPO","B1TE","B1TS","B1SEGUM","B1ALTER","B1CONTA","B1CC","B1ITEMCC","B1PROC","B1FORMLOT",
"B1GRUPCOM","B1CLVL","B1POSIPI","B1CODISS","B1ORIGEM","B1GRTRIB","B1TABIPI","B1CLASSE","B1ESTFOR","B1FORPRZ","B1TIPCAR","B1GRPCST","B1TPPROD","B1CODANT","B1GRPTI","B1PRDORI",
"B1TNATREC","B5ONU","B1GCCUSTO","B1PARCEI","B1CCCUSTO","B1CODQAD","B1TIPOBN","B5NATBEN","B5TPESOC","B5NBS","B5CODATIV","B5CDFATD","B5CODFAM","B5FORSER","B5MARPEC",
,"B5NATALBE","B5AGLUMRP","B5CODLIN","B5SERVINT","B5SERVENT","B5SERVSAI","B5SERVEMB","B5ENDECD",
"B5SERVTDV","B5ENDSAI","B5SERVDEV","B5SERVREQ","B5ENDENT","B5ENDREQ","B5ENDDEV","B5UMDIPI","B5PENE","B5UMPRC","B5CULTRA","B5CTVAR","B5CATEG",
"BZFILIAL","BZLOCPAD","BZORIGEM","BZFORPRZ","BZESTFOR","BZTE","BZTS"]; 

var arraysCamposFluig = []; 

var arraysCamposEditavel = []; 

var arraysCamposIntegravel = []; 

var arraysCamposDatasetClientes = []; 

var arraysCamposMaskMoney = [ "B1_PRV1", "B1_CUSTD", "B1_UPRC", "B1_COMIS", "B1_POTENCI", "B1_AFAMAD", "B1_PICM", "B1_IPI", "B1_ALIQISS", "B1_PICMRET",
  "B1_PICMENT","B1_REDINSS", "B1_REDIRRF", "B1_REDPIS", "B1_REDCOF", "B1_PCSLL", "B1_PCOFINS", "B1_PPIS", "B1_VLR_IPI", "B1_INT_ICM", 
  "B1_VLR_ICM","B1_VLR_PIS", "B1_AFABOV", "B1_VLR_COF", "B1_CRDEST", "B1_AFETHAB", "B1_AFACS", "B1_CRDPRES", "B1_ALFECRN", "B1_EMIN", 
  "B1_ESTSEG","B1_LE", "B1_LM", "B1_PERGART", "B1_MTBF", "B1_MTTR", "B1_FRACPER", "B1_LOTVEN", "B1_AFASEMT", "B1_AIMAMT", 
  "B1_AFUNDES","B1_PMACNUT", "B1_PMICNUT", "B1_VLCIF", "B1_PR43080", "B1_ALFECST", "B1_CFEMA", "B1_FECPBA", "B1_ALFECOP", "B1_ALFUMAC", 
  "B1_PRINCMG","B1_IMPNCM",
  "B5_PROPOR1","B5_PROPOR2","B5_CRDEST1","B5_CRDEST2","B5_FTIF","B5_FTIN","B5_DENSID","B5_CONCENT","B5_CODISRF","B5_VOLRECI","B5_DIASHL","B5_INSUMO","B5_PRODDNF","B5_ZF4PORC",
  "B5_AM4PORC","B5_VOLUME","B5_AMMULTS","B5_FCIPRV","B5_ZFMULTO","B5_ZFMULTS","B5_DIASHF","B5_MARGPRE","B5_VLRCID","B5_CODGNRE","B5_AMMULTO","B5_PRZCQ","B5_PRV2","B5_PRV7",
  "B5_BLQINVD","B5_QE1","B5_QE2","B5_COMPRLC","B5_EMPMAX","B5_COMPR","B5_ESPESS","B5_LARG","B5_CONVDIP","B5_IDADEM","B5_LVLEMB","B5_LPSEMB","B5_PERCUB","B5_CALORIA","B5_PESO",
  "B5_TOTGOR","B5_DIASES","B5_PRV3","B5_PRV4","B5_PRV5","B5_EAN141","B5_PRV6","B5_EAN145","B5_LARGLC","B5_ALTURLC","B5_PERIOT","B5_QEI","B5_QEL","B5_LEADTR","B5_FATARMA",
  "B5_ECPESOE","B5_ECALTEM","B5_ECLARGE","B5_ECLARGU","B5_ECCOMP","B5_ECPROFU","B5_ECCUBAG","B5_TOTGORS","B5_TOTGORT","B5_ALTURA","B5_EAN142","B5_EAN143","B5_EAN144","B5_EAN146","B5_EAN147","B5_EAN148",
  ]

var arraysCamposVisivelB5 = ["B5_COD","B5_CEME","B5_PROPOR1","B5_PROPOR2","B5_CRDEST1","B5_CRDEST2","B5_FTIF","B5_FTIN",
 "B5_USOITE","B5_CODISRF","B5_VOLRECI","B5_DIASHL","B5_INSUMO","B5_REVPROD","B5_CODTRAM","B5_TPSERV","B5_INDPETR","B5_DENSID",
 "B5_DTDECRE","B5_EMBAGRO","B5_REGMAPA","B5_PRODDNF","B5_INSSPAT","B5_PINSUMO","B5_BENDL","B5_IMPGRUP","B5_INTDI","B5_CONCENT",
 "B5_ZF4PORC","B5_AM4PORC","B5_LOCALIZ","B5_CODCAI","B5_VOLUME","B5_AMMULTS","B5_CONCEN","B5_DESCSER","B5_FILIAL","B5_LOCALI2",
 "B5_CODTP","B5_CMPEXTR","B5_CDDMDBA","B5_PERIOT","B5_ALTURLC","B5_SITDIEF","B5_DESCNFE","B5_TABINC","B5_CODGRU","B5_FORCAO","B5_MARCA","B5_SERSCD",
 "B5_FCIPRV","B5_ZFMULTO","B5_ZFMULTS","B5_DIASHF","B5_VLZERO","B5_2CODBAR","B5_NATBEN","B5_DTDECAL","B5_FUNCEP","B5_ECBENFI",
 "B5_NUMBEN","B5_ANOBEN","B5_TPESOC","B5_MARGPRE","B5_VLRCID","B5_ECEAN1","B5_ENVMKT","B5_ECDESF","B5_INDCPRB",
 "B5_NBS","B5_CODATIV","B5_CODSERC","B5_CATMAT","B5_CDFATD","B5_CODGNRE","B5_CODFAM","B5_DEC7174","B5_CLASSE","B5_ECALTEM",
 "B5_AMMULTO","B5_FORSER","B5_PROTOTI","B5_PRZCQ","B5_MARPEC","B5_MONTA","B5_PROJDES","B5_IDHIST","B5_EAN145",
 "B5_VERIND","B5_NRECAGR","B5_INGATV","B5_REDALIQ","B5_ISEN","B5_NUMBEAL","B5_NATALBE","B5_TPAPUR",
 "B5_CODITE","B5_FORMMRP","B5_AGLUMRP","B5_CTRWMS","B5_PRV2","B5_PROTCON","B5_TIPO","B5_GRPIVA","B5_FPRZCQ",
 "B5_PRV7","B5_CODCLI","B5_VERSAO","B5_BLQINVA","B5_ALTTRIB","B5_BLQINVD","B5_CODLIN","B5_DTREFP7","B5_EMB1","B5_EMB2",
 "B5_QE1","B5_QE2","B5_COMPRLC","B5_CTDACON","B5_ECSUBT","B5_ISDSHIP","B5_EMPMAX","B5_ROTACAO","B5_INSPAT","B5_CERT",
 "B5_SERVINT","B5_COMPR","B5_NPULMAO","B5_DES","B5_WMSEMB","B5_COMPEND","B5_ARREQTD","B5_ESPESS","B5_ESTMAT","B5_LARG",
 "B5_CONVDIP","B5_SERVTDV","B5_ENDSAI","B5_SERVDEV","B5_SERVREQ","B5_ENDENT","B5_ENDREQ","B5_ENDDEV","B5_CARPER","B5_IDADEM",
 "B5_LVLEMB","B5_LPSEMB","B5_PERCUB","B5_PORTMS","B5_UMDIPI","B5_ITEM","B5_CALORIA","B5_PESO","B5_TOTGOR","B5_DIASES",
 "B5_PRV3","B5_PRV4","B5_PRV5","B5_MODELO","B5_ESPECIE","B5_QUALIDA","B5_EAN141","B5_PRV6","B5_DTREFP2","B5_DTREFP3",
 "B5_DTREFP4","B5_DTREFP5", "B5_DTREFP6","B5_TIPUNIT","B5_LARGLC","B5_IMPETI","B5_VLDOPER","B5_VLDREQ","B5_ENDECD",
 "B5_SEMENTE","B5_LEADTR","B5_FATARMA","B5_UMIND","B5_SERVENT","B5_TAKEUP","B5_TPCOMMO","B5_SERVSAI","B5_SERVEMB", 
 "B5_ENDSCD","B5_ISIDUNI","B5_GSLE","B5_GSMC","B5_GSMI","B5_TPISERV","B5_ECDESCR","B5_ECENQUA","B5_ECPESOE",
 "B5_ECSEQ","B5_ECLARGE","B5_ECINDIC","B5_ECLARGU","B5_ECTITU","B5_ECPCHAV","B5_ECSEQ2","B5_ECCOMP","B5_ECPROFU", 
 "B5_ECCARAC","B5_ECCUBAG","B5_ECDTEX2","B5_ECDTLAN","B5_ECFLAG","B5_ECDTEX","B5_ECIMGFI","B5_ECAPRES","B5_SERECD", 
 "B5_ONU","B5_TOTGORS","B5_TOTGORT","B5_COR","B5_ALTURA","B5_EAN142","B5_EAN143","B5_EAN144","B5_EAN146","B5_EAN147",
 "B5_EAN148","B5_QTDVAR","B5_DTINV","B5_CODZON","B5_PENE","B5_TRATAM","B5_CLAUBA","B5_UMPRC","B5_DESTRAT","B5_CULTRA",
 "B5_CTVAR","B5_CATEG","B5NATBEN","B5TPESOC","B5NBS","B5CODATIV","B5CDFATD","B5CODFAM","B5FORSER",
 "B5MARPEC","B5NATALBE","B5CODGRP","B5CODITE","B5AGLUMRP","B5FPRZCQ","B5CODLIN","B5SERVINT",
 "B5SERVTDV","B5ENDSAI","B5SERVDEV","B5SERVREQ","B5ENDENT","B5ENDREQ","B5ENDDEV","B5UMDIPI",
 "B5SERVENT","B5SERVSAI","B5SERVEMB","B5ENDECD","B5ENDSCD","B5SERECD","B5SERSCD","B5ONU","B5CODZON",
 "B5PENE","B5UMPRC","B5CULTRA","B5CTVAR","B5CATEG"];

var arraysCamposZoomsB5 = ["B5_NATBEN","B5_TPESOC","B5_NBS","B5_CODATIV","B5_CDFATD","B5_CODFAM","B5_FORSER",
"B5_NATALBE","B5_CODITE","B5_AGLUMRP","B5_FPRZCQ","B5_CODLIN","B5_SERVINT",
"B5_SERVTDV","B5_ENDSAI","B5_SERVDEV","B5_SERVREQ","B5_ENDENT","B5_ENDREQ","B5_ENDDEV","B5_UMDIPI",
"B5_SERVENT","B5_SERVSAI","B5_SERVEMB","B5_ENDECD","B5_ENDSCD","B5_SERECD","B5_SERSCD","B5_ONU","B5_CODZON",
"B5_PENE","B5_UMPRC","B5_CULTRA","B5_CTVAR","B5_CATEG",]


var arraysCamposVisivelBZ = ["BZ_FILIAL","BZ_COD","BZ_LOCPAD","BZ_TE","BZ_TS","BZ_AFUNDES","BZ_ALFECRN","BZ_ALFUMAC","BZ_ALIQISS","BZ_COFINS",
 "BZ_CONINI","BZ_CONVDIP","BZ_CSLL","BZ_CTRWMS","BZ_CUSTD","BZ_DATREF","BZ_DTINCLU","BZ_EMAX","BZ_EMIN","BZ_ESTFOR","BZ_ESTSEG","BZ_FANTASM","BZ_FCIPRV","BZ_FECP","BZ_FECPBA",
 "BZ_FORPRZ","BZ_GRTRIB","BZ_HABDIF","BZ_HORFIX","BZ_IDHIST","BZ_IMPNCM","BZ_INT_ICM","BZ_IPI","BZ_IRRF","BZ_LE","BZ_LM","BZ_LOCALI2","BZ_LOCALIZ","BZ_MARKUP","BZ_MCUSTD","BZ_MOPC",
 "BZ_MRP","BZ_OPC","BZ_ORIGEM","BZ_PCOFINS","BZ_PCSLL","BZ_PE","BZ_PICM","BZ_PICMENT","BZ_PICMRET","BZ_PIS","BZ_PPIS","BZ_QB","BZ_QBP","BZ_QE","BZ_REDCOF","BZ_REDPIS","BZ_REVATU",
 "BZ_TIPE","BZ_TIPOCQ","BZ_TOLER","BZ_TPHOFIX","BZ_TRIBMUN","BZ_UCALSTD","BZ_UCOM","BZ_UPRC","BZ_VLR_ICM","BZ_VLR_IPI"]

var arraysCamposZoomsBZ = ["BZ_FILIAL","BZ_LOCPAD","BZ_ORIGEM","BZ_FORPRZ","BZ_ESTFOR","BZ_TE","BZ_TS"]

